[package]
name = "triton_grow"
version = "1.1.0"
authors = ["BradenEverson"]
description = "A self sustaining growing neural net that can repair itself until reaching a desired accuracy"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
