name: Unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install XLA
      run: wget https://github.com/elixir-nx/xla/releases/download/v0.6.0/xla_extension-x86_64-linux-gnu-cpu.tar.gz && tar -xzvf xla_extension-x86_64-linux-gnu-cpu.tar.gz
    - name: export env_vars
      run: export XLA_EXTENSION_DIR="xla/xla_extension" && export LD_LIBRARY_PATH="xla/xla_extension/lib"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
